# codemagic.yaml - Configuration pour build iOS sans compte Apple Developer payant
workflows:
  ios-dev-build:
    name: iOS Development Build
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios && pod install --repo-update

      - name: Build iOS (unsigned IPA for Sideloadly)
        script: |
          flutter build ios --release --no-codesign

      - name: Create unsigned IPA
        script: |
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r ../../../Vethome-unsigned.ipa Payload
          rm -rf Payload

    artifacts:
      - build/ios/iphoneos/Runner.app
      - "*.ipa"

    publishing:
      email:
        recipients:
          - ton-email@example.com  # Remplace par ton email
        notify:
          success: true
          failure: true

  # Build avec signing (quand tu auras le compte Apple Developer)
  ios-release:
    name: iOS Release Build (App Store)
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - ios_credentials  # À configurer dans Codemagic UI
      vars:
        BUNDLE_ID: com.vegece.app

    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Install CocoaPods
        script: cd ios && pod install --repo-update

      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_DEVELOPMENT
          keychain add-certificates
          xcode-project use-profiles

      - name: Build IPA
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
