# codemagic.yaml - Configuration pour build iOS sans compte Apple Developer payant
workflows:
  ios-dev-build:
    name: iOS Development Build (Unsigned for Sideloadly)
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get

      - name: Install CocoaPods
        script: cd ios && pod install --repo-update

      - name: Build unsigned app with xcodebuild
        script: |
          # Build directly with xcodebuild, bypassing Flutter's signing checks
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -derivedDataPath build/ios/derived \
            CODE_SIGN_IDENTITY="-" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            DEVELOPMENT_TEAM="" \
            clean build

      - name: Create unsigned IPA for Sideloadly
        script: |
          APP_PATH="build/ios/derived/Build/Products/Release-iphoneos/Runner.app"
          mkdir -p Payload
          cp -r "$APP_PATH" Payload/
          zip -r Vethome-unsigned.ipa Payload
          rm -rf Payload

    artifacts:
      - Vethome-unsigned.ipa
      - build/ios/derived/Build/Products/Release-iphoneos/Runner.app

    publishing:
      email:
        recipients:
          - ton-email@example.com  # Remplace par ton email
        notify:
          success: true
          failure: true

  # Build avec signing (quand tu auras le compte Apple Developer)
  ios-release:
    name: iOS Release Build (App Store)
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - ios_credentials  # À configurer dans Codemagic UI
      vars:
        BUNDLE_ID: com.vegece.app

    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Install CocoaPods
        script: cd ios && pod install --repo-update

      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_DEVELOPMENT
          keychain add-certificates
          xcode-project use-profiles

      - name: Build IPA
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
